///////////////////////////////////////////////////////////
//  NumberMath.as
//  Macromedia ActionScript Implementation of the Class NumberMath
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:06
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.math
{
	/**
	 * Math functions for Numbers (angles).
	 * @since		0.1
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.2
	 * @date 		12.01.2006*
	 * @created 26-VII-2006 13:46:07
	 */
	public class NumberMath
	{
	    static private var _2deg: Number = 180/Math.PI;
	    static private var _2rad: Number = Math.PI/180;

	    /**
	     * Transform a radian angle to degree.
	     * @return	The degree.
	     * 
	     * @param n    a radian number.
	     */
	    static public function toDegree(n:Number): Number
	    {
	    	return n*_2deg;
	    }

	    /**
	     * Transform a degree angle to radian.
	     * @return	The radian.
	     * 
	     * @param n    A degree number.
	     */
	    static public function toRadian(n:Number): Number
	    {
	    	return n*_2rad;
	    }

	}//end NumberMath

}