///////////////////////////////////////////////////////////
//  BitmapUtil.as
//  Macromedia ActionScript Implementation of the Class BitmapUtil
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:04
///////////////////////////////////////////////////////////



package sandy.util
{
	import flash.display.BitmapData;
	import flash.geom.*;
	import flash.display.Sprite;

	/**
	 * Utilities for the BitmapData object
	 * @version 1.0
	 * @created 26-VII-2006 13:46:04
	 */
	public class BitmapUtil
	{
	    /**
	     * 
	     * @param b
	     * @param scalex
	     * @param scaley
	     */
	    static public function getScaledBitmap(b:BitmapData, scalex:Number=1, scaley:Number=1):BitmapData
	    {
			var tex:BitmapData = new BitmapData( scalex * b.width, scaley * b.height);
			tex.draw( b, new Matrix( scalex, 0, scaley, 0 ) );
			return tex;
	    }

	    /**
	     * Convert a movieClip to a bitmapData. Take care of the movieclip position. The
	     * simple BitmapData.draw method doesn't take care of the negative part of the
	     * movieclip during the draw. This method does.
	     * @return BitmapData
	     * 
	     * @param mc    The movieClip to convert to a Bitmap
	     * @param pTransparent
	     * @param pColor
	     */
	    //static public function movieToBitmap(mc:MovieClip, pTransparent:Boolean, pColor:Number): BitmapData
	    static public function movieToBitmap(mc:Sprite, pTransparent:Boolean=true, pColor:Number=0x00FF00CC):BitmapData
	    {
	    	/**
			 * @modification Franto
			 * mc:Sprite - was mc:MovieClip
			 * _height, _width  => remove _
			 */
	    	var bmp:BitmapData;
			bmp = new BitmapData( mc.width, mc.height, pTransparent, pColor );
			bmp = new BitmapData( mc.width, mc.height, pTransparent );
			bmp.draw( mc );
			//
			return bmp;
	    }

	}//end BitmapUtil

}