///////////////////////////////////////////////////////////
//  Primitive3D.as
//  Macromedia ActionScript Implementation of the Interface Primitive3D
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:07
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////



package sandy.primitive
{
	/**
	 * Primitive3D
	 * <p>This is only an interface, to be sure all primitives Object have implements
	 * needed methods</p>
	 * @since		0.1
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.2
	 * @date 		12.01.2006
	 * @created 26-VII-2006 13:46:07
	 */
	public interface Primitive3D
	{
	    /**
	     * generate
	     * <p>generate all is needed to construct the Object3D : </p>
	     * <ul>
	     * <li>{@link Vertex}</li>
	     * <li>{@link UVCoords}</li>
	     * <li>{@link TriFace3D}</li>
	     * <li>{@link NFace3D} not implemented yet</li>
	     * </ul>
	     * <p>It can construct dynamically the object, taking care of your preferences
	     * given in arguments. <br/> Note in Sandy 0.1 all faces have only three points.
	     * This will change in the future version, and give to you the possibility to
	     * choose n points per faces</p>
	     * 
	     * @param Void
	     */
	    function generate():void;

	}//end Primitive3D

}