///////////////////////////////////////////////////////////
//  CamPathInterpolator.as
//  Macromedia ActionScript Implementation of the Class CamPathInterpolator
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:04
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////

import sandy.core.data.BezierPath;
import sandy.view.Camera3D;
import sandy.core.transform.BasicInterpolator;

package sandy.core.transform
{
	/**
	 * CamPathInterpolator
	 * @since		0.1
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.3
	 * @date 		28.03.2006
	 * @created 26-VII-2006 13:46:04
	 */
	public class CamPathInterpolator extends BasicInterpolator
	{
	    /**
	     * PRIVATE
	     */
	    private var _pPath: BezierPath;

	    /**
	     * Create a new CamPositionInterpolator.
	     * <p> This class realise a position interpolation the camera it has been applied
	     * to</p>
	     * <p> Be Carefull! This interpolator set the values as the camera's position!
	     * It's not an offset of position here.
	     * @param onFrames Number	The number of frames that would be used to do the
	     * interpolation. The smaller the faster the interpolation will be.
	     * 
	     * @param cam    Camera3D	The camera that will be updated by the Interpolator.
	     * @param f    Function 	The function generating the interpolation value. You can
	     * use what you want even if Sandy recommends the Ease class The function must
	     * return a number between [0,1] and must have a parameter between [0,1] too.
	     * @param pnFrames
	     * @param path    BezierPath The path.
	     */
	    public function CamPathInterpolator(cam:Camera3D, f:Function, pnFrames:Number, path:BezierPath)
	    {
	    }

	    /**
	     * 
	     * @param Void
	     */
	    public function render(Void): Void
	    {
	    }

	}//end CamPathInterpolator

}