///////////////////////////////////////////////////////////
//  IScreen.as
//  Macromedia ActionScript Implementation of the Interface IScreen
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:06
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.view
{
	import flash.display.Sprite;
	import flash.geom.Rectangle;
	
	import sandy.view.Camera3D;
	/**
	 * IScreen
	 * @since		0.1
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.2
	 * @date 		12.01.2006
	 * @created 26-VII-2006 13:46:06
	 */
	public interface IScreen
	{
	    /**
	     * Destroy the screen.
	     */
	    function dispose():void;
		
		function free():void;
		
	    /**
	     * Return the clip container.
	     * @return	The clip container.
	     */
	    function getContainer():Sprite;

	    /**
	     * Returns the rectangle representing the screen dimensions.
	     * @return	A Rectangle.
	     */
	    function getSize():Rectangle;

	    /**
	     * Render the array of {@code Face} passed in arguments.
	     * @param	A The Array of {@code Face}.
	     * 
	     * @param a
	     */
	    function render(a:Array):void;

	    /**
	     * Set the {@code Camera3D} for the screen.
	     * 
	     * @param c    The {@code Camera3D}.
	     */
	    function setCamera(c:Camera3D):void;
	}//end IScreen
}