///////////////////////////////////////////////////////////
//  BSphere.as
//  Macromedia ActionScript Implementation of the Class BSphere
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:04
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.core.data
{
	import sandy.core.data.Vertex;
	import sandy.core.Object3D;
	/**
	 * Bounding Sphere object used to clip the object faster.
	 * <p>Create a bounding Sphere that contains the whole object</p>
	 * @author 	Thomas Pfeiffer - kiroukou
	 * @version 1.0
	 * @date 	05.08.2006
	 * @created 26-VII-2006 13:46:04
	 */
	public final class BSphere
	{
	    public var center:Vertex;
	    public var owner:Object3D;
	    public var radius:Number;

	    /**
	     * <p>Create a new {@code BSphere} Instance</p>
	     * @param	pos	The center of the sphere
	     * @param	radius	THe radius of the Sphere
	     * 
	     * @param obj
	     * @param ppos
	     * @param pradius
	     */
	    public function BSphere(obj:Object3D, ppos:Vertex, pradius:Number)
	    {
	    }

	    /**
	     * Create a BSphere object, representing a Bounding Sphere volume englobing the 3D
	     * object passed in parameters. Verry usefull for clipping and so performance !
	     * 
	     * @param obj    Object3D The object that you want to add a bounding Sphere volume.
	     */
	    static public function create(obj:Object3D): BSphere
	    {
	    }

	    /**
	     * Get a String represntation of the {@code BSphere}.
	     * @return	A String representing the Bounding Sphere
	     * 
	     * @param Void
	     */
	    public function toString(Void): String
	    {
	    }

	}//end BSphere

}