///////////////////////////////////////////////////////////
//  TransformType.as
//  Macromedia ActionScript Implementation of the Class TransformType
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:10
//  Original author: Thomas PFEIFFER
///////////////////////////////////////////////////////////
package sandy.core.transform
{
	/**
	 * Contains all the types of transformation that can be used in Sandy.
	 * @author Thomas PFEIFFER
	 * @version 1.0
	 * @date 	05.08.2006
	 * @created 26-VII-2006 13:46:10
	 */
	public class TransformType
	{
	    /**
	     * Constant value representing a mixed transformation(2 or more transformations
	     * combined)
	     */
	    static public const MIXED:uint = 0;

	    /**
	     * Constant value representing no Transformation
	     */
	    static public const NONE:uint = 1;

	    /**
	     * Constant value representing a Rotation
	     */
	  	static public const ROTATION:uint = 2;

	    /**
	     * Constant value representing a rotation Interpolation
	     */
		static public const ROTATION_INTERPOLATION:uint = 3;

	    /**
	     * Constant value representing a Scale
	     */
	     static public const SCALE:uint = 4;

	    /**
	     * Constant value representing a Scale Interpolation
	     */
		static public const SCALE_INTERPOLATION:uint = 5;

	    /**
	     * Constant value representing a Translation
	     */
		static public const TRANSLATION:uint = 6;

	    /**
	     * Constant value representing a translation Interpolation
	     */
	    static public const TRANSLATION_INTERPOLATION:uint = 7;
	    
	    /**
	     * Constant value representing a position Interpolation along a Bezier 3D path
	     */
	    static public const PATH_INTERPOLATION:uint = 8;
	    
	    /**
	     * Constant value representing a vertex Interpolation
	     */
	    static public const VERTEX_INTERPOLATION:uint = 9;
	    
	    /**
	     * Constant value representing a vertex Interpolation
	     */
	    static public const KEYFRAME_INTERPOLATION:uint = 10;
	}
}