///////////////////////////////////////////////////////////
//  Quaternion.as
//  Macromedia ActionScript Implementation of the Class Quaternion
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:08
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////

package sandy.core.data
{
	import sandy.core.data.Vector;
	
	/**
	 * @since		0.3
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.3
	 * @date 		28.03.2006 Experimental class. It is
	 * @created 26-VII-2006 13:46:08
	 */
	public class Quaternion extends Vector
	{
	    public var w: Number;

	    /**
	     * 
	     * @param px
	     * @param py
	     * @param pz
	     * @param pw
	     */
	    public function Quaternion(px:Number = 0, py:Number = 0, pz:Number = 0, pw:Number = 0)
	    {
	    	super( px, py, pz );
			w = pw;
	    }

	    /**
	     * 
	     * @param Void
	     */
	    public override function toString(): String
	    {
	    	var s:String = new String("");
			s += "Quaternion x:"+x+" , y:"+y+", z:"+z+" w:"+w;
			return s;
	    }

	}//end Quaternion

}