///////////////////////////////////////////////////////////
//  NCurvedFace3D.as
//  Macromedia ActionScript Implementation of the Class NCurvedFace3D
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:06
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.core.face
{
	import sandy.core.face.NFace3D;
	import sandy.core.Object3D;
	import sandy.core.data.UVCoord;
	import sandy.skin.Skin;
	import sandy.skin.SkinType;
	
	import flash.display.Sprite;
	/**
	* NCurvedFace3D
	* <p>Allows to create a curved face with N points. Very usefull to create complex shapes/objects.</p>
	* @author		Thomas Pfeiffer - kiroukou
	* @version		1.0
	* @date 		05.08.2006 
	**/
	public class NCurvedFace3D extends NFace3D
	{
		public function NCurvedFace3D(  oref:Object3D, a:Array)
		{
			super( oref, a );
		}
		
		/**
		* Allows you to get the vertex of the face. Very usefull when you want to make some calculation on a face after it has been clicked.
		* @param	Void
		* @return Array The array of vertex.
		*/
		public function getVertex():Array
		{
			return _aVertex;
		}
		
		/** 
		 * Render the face into a MovieClip.
		 *
		 * @param	{@code mc}	A {@code MovieClip}.
		 * @param	id			A Number which is the camera identifiant
		 */
		public function render( mc:Sprite ):void
		{
			_mc = mc;
			var i:uint = 0;
			// --
			if( _bEv) __prepareEvents( mc );
			( _bV ) ? _s.begin( this, mc ) : _sb.begin( this, mc );
			// --
			mc.moveTo( _va.sx, _va.sy );
			for( i = 0; i < _nL; i += 2 )
			{
				mc.curveTo( _aVertex[i].sx, _aVertex[i].sy, _aVertex[i+1].sx, _aVertex[i+1].sy);
			}
			// -- we launch the rendering with the appropriate skin
			( _bV ) ? _s.end( this, mc ) : _sb.end( this, mc );
		}
	
		/** 
		 * Refresh the face display
		 */
		public function refresh():void
		{
			_mc.clear();
			( _bV ) ? _s.begin( this, _mc ) : _sb.begin( this, _mc );
			//
			_mc.moveTo( _va.sx, _va.sy );
			var i:Number = 0;
			for( i = 0; i < _nL; i += 2 )
			{
				_mc.curveTo( _aVertex[i].sx, _aVertex[i].sy, _aVertex[i+1].sx, _aVertex[i+1].sy);
			}
			// -- we launch the rendering with the appropriate skin
			( _bV ) ? _s.end( this, _mc ) : _sb.end( this, _mc );
		}
		
		/**
		* Get a String represntation of the {@code NFace3D}.
		* 
		* @return	A String representing the {@code NFace3D}.
		*/
		public function toString(): String
		{
			return new String("sandy.core.face.NCurvedFace3D");
		}
	
	}

}