///////////////////////////////////////////////////////////
//  SimpleLineSkin.as
//  Macromedia ActionScript Implementation of the Class SimpleLineSkin
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:08
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.skin
{
	import sandy.core.face.Face;
	import sandy.skin.SkinType;
	import sandy.skin.Skin;
	import sandy.skin.BasicSkin;
	
	import flash.display.Sprite;
	/**
	 * SimpleLineSkin
	 * @author 	Thomas Pfeiffer - kiroukou
	 * @version 1.0
	 * @date 	05.08.2006
	 * @created 26-VII-2006 13:46:08
	 */
	public class SimpleLineSkin extends BasicSkin implements Skin
	{
		/////////////
		// SETTERS //
		/////////////
		public function set alpha( n:Number ):void
		{
			_alpha = n;
			dispatchEvent( _eOnUpdate );
		}
		public function set color( n:uint ):void
		{
			_color = n;
			dispatchEvent( _eOnUpdate );
		}
		public function set thickness( n:uint ):void
		{
			_thickness = n;
			dispatchEvent( _eOnUpdate );
		}	
		/////////////
		// GETTERS //
		/////////////	
		public function get alpha():Number
		{
			return _alpha;
		}
		public function get color():uint
		{
			return _color;
		}	
		public function get thickness():uint
		{
			return _thickness;
		}	
			
		/**
		 * getType, returns the type of the skin
		 * @param Void
		 * @return	The appropriate SkinType
		 */
		 public override function getType ():uint
		 {
		 	return SkinType.SIMPLE_LINE;
		 }
		
		/**
		 * Start the rendering of the Skin
		 * @param f	The face which is being rendered
		 * @param mc The mc where the face will be build.
		 */ 	
		public function begin( f:Face, content:Sprite ):void
		{
			content.filters = _filters;
			content.graphics.lineStyle( thickness, color, alpha);
		}
		
		/**
		 * Finish the rendering of the Skin
		 * @param f	The face which is being rendered
		 * @param mc The mc where the face will be build.
		 */ 	
		public function end( f:Face, mc:Sprite ):void
		{
			; // nothing here
		}
	    /**
	     * Create a new SimpleLineSkin
	     * 
	     * @param t    The size of line
	     * @param c    The color ot the line
	     * @param a    The alpha of the line
	     */
	    public function SimpleLineSkin( t:uint=2, c:uint=0, a:Number=1 )
	    {
		    super();
			_thickness 	=  t;
			_color 		=  c;
			_alpha 		=  a;
	    }

	    /**
	     * 
	     * @param Void
	     */
	    public override function toString():String
	    {
	    	return 'sandy.skin.SimpleLineSkin';
	    }
	  
		private var _color:uint;// Color of the lines
		private var _thickness:uint;// Thickness of the lines
		private var _alpha:Number;// Alpha transparency of the lines

	}//end SimpleLineSkin

}