///////////////////////////////////////////////////////////
//  Leaf.as
//  Macromedia ActionScript Implementation of the Class Leaf
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:06
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////

package sandy.core.group
{
	import sandy.core.group.Node;
	import sandy.core.group.INode;	
	/**
	 * <p>Abstract class used to represent the Leaf of the Sandy's scene tree. This
	 * class should not be used directly, except for typing purpose. This class is
	 * basically the same as the Node one, except that your can't add/remove some
	 * children </p>
	 * @author 	Thomas Pfeiffer - kiroukou
	 * @version 1.0
	 * @date 	05.08.2006
	 * @created 26-VII-2006 13:46:06
	 */
	public class Leaf extends Node implements INode
	{
	    /**
	     * Do nothing since a leaf is the lower part of a tree. It cannot have a child.
	     * @param n Node The Node to set as a child of the current node. But it will not
	     * be done !
	     * @return
	     * 
	     * @param child
	     */
	    public override function addChild( child:Node ):void
	    {
	    	;
	    }

	    /**
	     * @param parent
	     */
	    function Leaf()
	    {
	    	super();
	    }

	    /**
	     * Does nothing since a Leaf doesn't have some children. Return false.
	     * @return Boolean Return everytime false value;
	     * 
	     * @param child    Node The node you want to remove.
	     */
	    public override function removeChild(child:Node):Boolean
	    {
	    	return false;
	    }
	    	    
	    public function render():void
		{
			;
		}
		
		public function dispose():void
		{
			;
		}
		
		public override function toString():String
		{
			return 'sandy.core.group.Leaf';
		}
	}//end Leaf
}