///////////////////////////////////////////////////////////
//  TreeEvent.as
//  Macromedia ActionScript Implementation of the Class TreeEvent
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:10
//  Original author: Thomas
///////////////////////////////////////////////////////////



package sandy.events
{
	/**
	 * Stupid Event class used for the test
	 * @author Thomas
	 * @version 1.0
	 * @created 26-VII-2006 13:46:10
	 */
	public class TreeEvent extends BasicEvent
	{
	    static public var EVENT: EventType = new EventType( 'onTreeEvent' );

	    /**
	     * 
	     * @param e
	     * @param oT
	     */
	    public function TreeEvent(e:EventType, oT)
	    {
	    }

	}//end TreeEvent

}