///////////////////////////////////////////////////////////
//  Interpolator3D.as
//  Macromedia ActionScript Implementation of the Interface Interpolator3D
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:06
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.core.transform
{
	import sandy.core.transform.ITransform3D;
	/**
	 * Represents a Transformation Interpolator for an Group.
	 * <p>The Interpolator3D is applied to each Object3D into a Group.</p>
	 * @author 	Thomas Pfeiffer - kiroukou
	 * @version 1.0
	 * @date 	05.08.2006
	 * @created 26-VII-2006 13:46:06
	 */
	public interface Interpolator3D extends ITransform3D
	{
	    /**
	     * Returns the current percent of the Interpolation
	     * 
	     * @param Void
	     */
	    function getPercent():Number;

	    /**
	     * Let the interpolator do a new loop
	     * 
	     * @param Void
	     */
	    function redo():void;

	    /**
	     * setDuration
	     * @return
	     * 
	     * @param t    Number The number of frames that you want the interpolation last
	     */
	    function setDuration(t:Number):void;

	    /**
	     * Make the Interpolator reverse its movement
	     * 
	     * @param Void
	     */
	    function yoyo():void;

	}//end Interpolator3D

}