///////////////////////////////////////////////////////////
//  ITransform3D.as
//  Macromedia ActionScript Implementation of the Interface ITransform3D
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:06
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.core.transform
{
	import sandy.core.data.Matrix4;
	import sandy.core.transform.TransformType;
	
	import flash.events.IEventDispatcher;
	/**
	 * Represents a Transformation for an Group.
	 * <p>The Transform3D is applied to each Object3D into a Group.</p>
	 * @since		0.1
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.2
	 * @date 		12.01.2006
	 * @created 26-VII-2006 13:46:06
	 */
	public interface ITransform3D extends IEventDispatcher
	{
		function setModified( b:Boolean ):void;
		function isModified():Boolean;	   
		
	    /**
	     * Get the amtrix of the transformation
	     * @return	Matrix4 The matrix
	     * 
	     * @param Void
	     */
	    function getMatrix():Matrix4;

	    /**
	     * Get the type of the Transform3D.
	     * @return	The type of the transformation.
	     * 
	     * @param Void
	     */
	    function getType():uint;

	}//end ITransform3D
}