///////////////////////////////////////////////////////////
//  Plane.as
//  Macromedia ActionScript Implementation of the Class Plane
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:07
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////



package sandy.core.data
{
	/**
	 * Plane representation in a 3D space. Used maily to represent the frustrum planes
	 * of the camera This class is not used yet in Sandy.
	 * @since		0.3
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.1
	 * @date 		22.02.2006
	 * @created 26-VII-2006 13:46:07
	 */
	public class Plane
	{
	    public var a: Number;
	    public var b: Number;
	    public var c: Number;
	    public var d: Number;

	    /**
	     * <p>Create a new {@code Plane} Instance</p>
	     * 
	     * @param a    the first plane coordinate
	     * @param b    the second plane coordinate
	     * @param c    the third plane coordinate
	     * @param d    the forth plane coordinate
	     */
	    public function Plane(a:Number, b:Number, c:Number, d:Number)
	    {
	    }

	    /**
	     * Get a String represntation of the {@code Plane}.
	     * @return	A String representing the {@code Plane}.
	     * 
	     * @param Void
	     */
	    public function toString(): String
	    {
	    	return "sandy.core.data.Plane";
	    }

	}//end Plane

}