///////////////////////////////////////////////////////////
//  TransformEvent.as
//  Macromedia ActionScript Implementation of the Class TransformEvent
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:09
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////
package sandy.events
{
	import flash.events.Event;
	/**
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 1.0
	 * @date 	05.08.2006
	 * @created 26-VII-2006 13:46:09
	 */
	public class TransformEvent extends Event
	{
	    private var _nType:uint;
	    /**
	     * The Interpolation end Event. Broadcasted when the Interpolation is finished
	     */
	    static public const onEndEVENT:String = "onEnd";
	    /**
	     * The Interpolation start Event. Broadcasted when the Interpolation is started
	     */
	    static public const onStartEVENT:String = "onStart";
	    /**
	     * Return the type of transformation
	     * @return uint The transformation ID
	     * @param Void
	     */
	    public function geTransformType():uint
	    {
	    	return _nType
	    }
	    
	    /**
	     * Set the type of transformation
	     * @type uint The type of transformation
	     */  
	    public function setTransformType( type:uint ):void
	    {
	    	_nType = type;
	    }

	    /**
	     * Constructor 
	     * @param e String the Event type
	     * @param type The kind of transformation
	     */
	    public function TransformEvent(e:String, type:uint)
	    {
	    	super( e, false, false );
	    	_nType = type;
	    }
	}//end TransformEvent
}