///////////////////////////////////////////////////////////
//  VideoSkin.as
//  Macromedia ActionScript Implementation of the Class VideoSkin
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:11
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////

package sandy.skin
{
	import flash.display.BitmapData;
	import sandy.core.face.Face;
	import sandy.core.light.Light3D;
	import sandy.core.World3D;
	import sandy.math.VectorMath;
	import sandy.skin.Skin;
	import sandy.skin.SkinType;
	import sandy.skin.TextureSkin;
	import flash.media.Video;
	import flash.events.Event;

	/**
	 * VideoSkin Allow you to texture a 3D Object with a movieClip wich contains
	 * animation, picture, or video.
	 * @since		1.0
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 1.0
	 * @date 		22.04.2006
	 * @created 26-VII-2006 13:46:11
	 */
	public class VideoSkin extends TextureSkin
	{
		
	    /**
	     * --
	     */
	    private var _video: Video;

	    /**
	     * Create a new VideoSkin.
	     * 
	     * @param video    Video a video object instance
	     */
	    public function VideoSkin(video:Video)
	    {
	    	super( new BitmapData( video.width, video.height ) );
			_video = video;
			// TODO: Think again on which choice is clever, choosing the World3D framerate to update the texture
			// or to use the texture movieClip framerate as timer to update the bitmap.
			World3D.addEventListener( World3D.onRenderEVENT, __updateTexture );
	    }
	    
	    private function __updateTexture(e:Event): void
	    {
	    	texture.draw( _video );
			// le broadcast ne se fait pas tout seul? car pas de set texture() de r�aliser?
			// TODO: what shoud be here, dispatchEvent => there is some error with casting
			// please look at this
			//dispatchEvent( _eOnUpdate );
	    }

	    /**
	     * getType, returns the type of the skin
	     * @return	The appropriate SkinType
	     * 
	     * @param Void
	     */
	    public override function getType(): uint
	    {
	    	return SkinType.VIDEO;
	    }

	    /**
	     * 
	     * @param Void
	     */
	    public override function toString(): String
	    {
	    	return 'sandy.skin.VideoSkin';
	    }



	}//end VideoSkin

}