///////////////////////////////////////////////////////////
//  Rectangle.as
//  Macromedia ActionScript Implementation of the Class Rectangle
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:08
//  Original author: Thomas Pfeiffer - kiroukou
///////////////////////////////////////////////////////////



package sandy.util
{
	/**
	 * Rectangle
	 * <p> wrapper to MM Flash8 Rectangle class. Useful to store area dimension, and
	 * having our class allows to export in player 6 and 7 easily </p>
	 * @since		0.1
	 * @author Thomas Pfeiffer - kiroukou
	 * @version 0.2
	 * @date 		12.01.2006
	 * @created 26-VII-2006 13:46:08
	 */
	public class Rectangle
	{
	    /**
	     * height Number Width of the Rectangle
	     */
	    public var height:Number;
	    /**
	     * width Number Width of the Rectangle
	     */
	    public var width:Number;
	    /**
	     * x Number Position of the top left corner of the Rectangle horizontally
	     */
	    public var x:Number;
	    /**
	     * y Number Position of the top left corner of the Rectangle vertically
	     */
	    public var y:Number;

	    /**
	     * Constructor of the Rectangle class default values are 0 as width, height, and
	     * corner position.
	     * 
	     * @param px
	     * @param py
	     * @param pwidth
	     * @param pheight
	     */
	    public function Rectangle(px:Number = 0, py:Number = 0, pwidth:Number = 0, pheight:Number = 0)
	    {
	    	x = px;
		 	y = py;
		 	width = pwidth;
		 	height = pheight;
	    }

	}//end Rectangle

}