///////////////////////////////////////////////////////////
//  SkinType.as
//  Macromedia ActionScript Implementation of the Class SkinType
//  Generated by Enterprise Architect
//  Created on:      26-VII-2006 13:46:09
//  Original author: Thomas Pfeiffer - Kiroukou
///////////////////////////////////////////////////////////

package sandy.skin
{
	/**
	 * Contains all the types of skins that can be used in Sandy.
	 * @author Thomas Pfeiffer - Kiroukou
	 * @version 0.2
	 * @date 		12.01.2006
	 * @created 26-VII-2006 13:46:09
	 */
	public class SkinType
	{
	   	/**
	     * Constant value representing the ZLightenSkin
	     */
	    static public const NONE:uint = 0;
	    /**
	     * Constant value representing the MovieSkin
	     */
		static public const MOVIE:uint = 1;
	    /**
	     * Constant value representing the SimpleColorSkin
	     */
		static public const SIMPLE_COLOR:uint = 2;
	    /**
	     * Constant value representing the SimpleLineSkin
	     */
		static public const SIMPLE_LINE:uint = 3;
	    /**
	     * Constant value representing the SimpleLineSkin
	     */
	    static public const TEXTURE:uint = 4;
	    /**
	     * Constant value representing the VideoSkin
	     */ 
		static public const VIDEO:uint = 5;
	    /**
	     * Constant value representing the ZLightenSkin
	     */
	    static public const ZLIGHTEN:uint = 6;
	   	/**
	     * Constant value representing the SMixedSkin
	     */
	    static public const MIXED:uint = 7;
	}//end SkinType
}